api/urls.py
from django.urls import path

from api import views


app_name = 'api'
urlpatterns = [
    path('student/list', views.ApiStudentLV.as_view(), name='student_list'),
    path('student/add', views.AddStudentCV.as_view(), name='student_list'),
    path('student/<int:student_id>/', views.ApiStudentDV.as_view(), name='student_detail'),
    path('report/submit/<int:student_id>/', views.ApiSubmitCV.as_view(), name='submit'),
    path('report/result/<int:student_id>/', views.ApiResultLV.as_view(), name='result'),
    path('report/detail/<int:student_id>/', views.ApiReportLV.as_view(), name='result'),
]

mpitest/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from mpitest.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('report/', include('report.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users.views import CustomPasswordChangeView, EditUserProfileView, PaymentResultView, PaymentSuccessView, PaymentView, SignUpView, CustomLoginView

app_name = "users"
urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', EditUserProfileView.as_view(), name='profile'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('payment/result/', PaymentResultView.as_view(), name='payment_result'),
    path('payment/success/', PaymentSuccessView.as_view(), name='payment_success'),
]

templates/include/add_student_vue.html
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>
const TestSubmitApp = {
  delimiters: ['[[', ']]'],
  data() {
    return {
      csrfToken: document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
      studentName: "",
      birthdate: "",
      grade: "",
    };
  },
  methods: {
    submitForm() {
      // 이름 유효성 검사
      if (!this.studentName) {
        alert("이름을 입력하세요");
        return;
      }

      // 생년월일 유효성 검사
      if (!this.birthdate.match(/^\d{8}$/)) {
        alert("생년월일을 8자리로 입력하세요");
        return;
      }

      // 학년 유효성 검사
      if (!this.grade) {
        alert("학년을 선택하세요");
        return;
      }

      const studentBD = this.birthdate.replace(/(\d{4})(\d{2})(\d{2})/, '$1-$2-$3');
      // FormData 인스턴스 생성
      const formData = new FormData();
      
      // 데이터 추가
      formData.append('name', this.studentName);
      formData.append('birthdate', studentBD);
      formData.append('grade', this.grade);

      axios.post(`/api/student/add`, formData, {
        headers: {
          'X-CSRFToken': this.csrfToken,
          'Content-Type': 'multipart/form-data'
        }
      })
      .then(response => {
        console.log("Submit response:", response);
        window.location.href = `/`;
      })
      .catch(error => {
        console.error("Submit error:", error.response);
        alert(`${error.response.status} ${error.response.statusText}`);
      });
    }
  },
}
Vue.createApp(TestSubmitApp).mount('#page-top');
</script>

templates/include/auth_vue.html
<script>
  document.getElementById('signupForm').addEventListener('submit', function(event) {
    // Make sure the telephone_part1 is included in the form submission
    var telephone_part1 = document.createElement('input');
    telephone_part1.setAttribute('type', 'hidden');
    telephone_part1.setAttribute('name', 'telephone_part1');
    telephone_part1.setAttribute('value', '010');
    this.appendChild(telephone_part1);
  });
    // HTML5 폼 유효성 검사가 비활성화된 경우, 이를 다시 활성화합니다.
  document.getElementById('signupForm').addEventListener('submit', function(e) {
    if (!this.checkValidity()) {
      e.preventDefault(); // 폼 제출 방지
      e.stopPropagation(); // 상위 요소로의 이벤트 전파 중지
    }
    this.classList.add('was-validated');
  }, false);
</script>

templates/include/change_password_vue.html
<script>
    document.getElementById('passwordChangeForm').addEventListener('submit', function(event) {
        const oldPasswordErrors = '{{ form.old_password.errors }}';
        if (oldPasswordErrors) {
            event.preventDefault();
            alert("입력하신 현재 비밀번호가 틀립니다.");
        }
    });
</script>

templates/include/edit_profile_vue.html
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict'
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')
        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }
                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>

templates/include/payment_vue.html
<script src="https://cdn.iamport.kr/v1/iamport.js"></script>
<script>
document.addEventListener("DOMContentLoaded", function() {
    function initiatePayment() {
        var paymentType = document.getElementById('paymentType').value;
        var amount = paymentType === 'single' ? 1000 : 10000; // 단일 결제는 1000원, 대량 결제는 10000원
        var merchantUid = `payment-${crypto.randomUUID()}`;

        var IMP = window.IMP;
        IMP.init('{{ api_key }}');  // 가맹점 식별코드 설정에서 가져오기
        IMP.request_pay({
            pg: 'html5_inicis'.'INIpayTest',
            pay_method: 'card',
            merchant_uid: merchantUid,
            name: paymentType === 'single' ? '단일 결제' : '대량 결제',
            amount: amount,
            buyer_email: '{{ user.email }}',
            buyer_name: '{{ user.username }}',
            buyer_tel: '{{ user_profile.telephone }}',
            buyer_addr: '{{ user_profile.region_detail}}',
            buyer_postcode: '00000'
        }, function (rsp) {
            if (rsp.success) {
                fetch("{% url 'users:payment_result' %}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": "{{ csrf_token }}"
                    },
                    body: JSON.stringify({
                        imp_uid: rsp.imp_uid,
                        merchant_uid: rsp.merchant_uid,
                        payment_type: paymentType
                    })
                }).then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                        alert('결제가 완료되었습니다.');
                        window.location.href = "{% url 'users:payment_success' %}";
                    } else {
                        alert('결제에 실패했습니다: ' + data.message);
                    }
                });
            } else {
                alert('결제에 실패했습니다. 에러 내용: ' + rsp.error_msg);
            }
        });
    }
    window.initiatePayment = initiatePayment;
});

// 나중에 결제 붙일 때 써먹기
</script>

templates/include/student_detail_vue.html
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>
  const StudentDetailApp = {
    delimiters: ['[[', ']]'],
    data() {
      return {
        csrfToken : document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
        studentname: '',
        TestList: {},
        studentId: '',
        errorMessage: [],
      }
    },
    created() {
      console.log("created()...");
      let path = window.location.pathname; // 현재 페이지의 경로를 가져옵니다.
      if (!path.endsWith('/')) {
        path += '/';
      }
      this.studentId = path.split('/').slice(-2)[0];
      this.fetchStudentDetail(this.studentId);
    },
    methods: {
      fetchStudentDetail(studentId) {
        console.log("fetchStudentDetail()...", studentId);
        axios.get(`/api/student/${studentId}`)
          .then(res => {
            console.log("FETCH STUDENTDETAIL GET RES", res);
            this.studentname = res.data.student_name;
            // console.log("student name :", this.student_name)
            this.TestList = res.data.tests.map(test => {
              // 시험 이름(또는 설명)을 구성합니다.
              const semesterStr = test.test_semester === 1 ? "상반기" : "하반기";
              const test_name = `${test.test_year}년도 ${semesterStr} ${test.ExamGrade}학년`;
              return {
                ...test,
                test_name,  // 구성한 시험 이름을 객체에 추가합니다.
              };
            });            
            console.log("TestList : ", this.TestList)
            console.log("student name : ", this.studentname)
          })
          .catch(err => {
            console.log("FETCH STUDENTDETAIL GET ERR.RESPONSE", err.response);
            alert(`${err.response.status} ${err.response.statusText}`);
          });
      },
      submitTest() {
        console.log("submitTest() with studentId:", this.studentId);
        // studentId를 포함한 API 요청을 보내는 로직
        axios.get(`/api/report/submit/${this.studentId}/`, {})
          .then(res => {
            if (res.data.status === 'error') {
              this.errorMessage = this.parseMessage(res.data.message);

              var paymentModal = new bootstrap.Modal(document.getElementById('paymentModal'), {});
              paymentModal.show();
            } else {
              window.location.href = `/report/submit/${this.studentId}`;
            }
          })
          .catch(err => {
            if (err.response && err.response.data && err.response.data.message) {
              this.errorMessage = err.response.data.message;
            } else {
              this.errorMessage = `${err.response.status} ${err.response.statusText}`;
            }
            this.errorMessage = this.parseMessage(res.data.message);
            var paymentModal = new bootstrap.Modal(document.getElementById('paymentModal'), {});
            paymentModal.show();
          });
      },
      navigateToReport(test){
        const year_semester = `${test.test_year}${test.test_semester}`;
        const url = `/report/result/${this.studentId}/?year_semester=${year_semester}&test_grade=${test.ExamGrade}`;

        window.location.href = url;
      },
      editTestResult(testResultId) {
        console.log("test result id : ", testResultId)
        // 시험 결과 수정 페이지로 리다이렉트
        window.location.href = `/report/result/update/${testResultId}/`;
      },
      parseMessage(message) {
        // 메시지를 문장 단위로 분할하여 배열로 반환
        return message.split('.').filter(sentence => sentence.trim().length > 0).map(sentence => sentence.trim());
      },
      goToPayment() {
//        window.location.href = '{% url "users:payment" %}';
//        나중에 결제 붙일 때 써먹기
        const modal = document.getElementById('paymentModal');
        const bootstrapModal = bootstrap.Modal.getInstance(modal);
        bootstrapModal.hide();
      },
    }
  }
  Vue.createApp(StudentDetailApp).mount('#page-top');
</script>

templates/include/student_list_vue.html
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>
    const StudentListApp = {
        delimiters: ['[[', ']]'],
        data() {
            return {
                studentList: [],
            }
        },
        created() {
            console.log("created()...");
            this.fetchStudentList();
        },
        methods: {
            fetchStudentList() {
                console.log("fetchStudentList()...");
                axios.get('/api/student/list')
                    .then(res => {
                        console.log("FETCH STUDENTLIST GET RES", res);
                        this.studentList = res.data;
                    })
                    .catch(err => {
                        console.log("FETCH STUDENTLIST GET ERR.RESPONSE", err.response);
                        alert(`${err.response.status} ${err.response.statusText}`);
                    });
            },
            addStudent() {
                console.log("addStudent()...");
                axios.get('/api/student/add')
                    .then(res => {
                        console.log("FETCH STUDENT ADD GET RES", res)
                        window.location.href = `/dashboard/addstudent/`;

                    })
                    .catch(err => {
                        console.log("FETCH STUDENT ADD GET ERR.RESPONSE", err.response)
                        alert(`${err.response.status} ${err.response.statusText}`)
                    })
            },
        }
    }

    Vue.createApp(StudentListApp).mount('#page-top')
</script> 

templates/include/test_list_vue.html
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>
  const TestListApp = {
    delimiters: ['[[', ']]'],
    data() {
      return {
        studentname: '',
        TestList: {},
      }
    },
    created() {
      console.log("created()...");
      // const studentId = location.pathname.split('/')[3]
      // this.fetchStudentDetail(studentId);
    },
    methods: {
      fetchStudentDetail(studentId) {
        console.log("fetchStudentDetail()...", studentId);
        <!-- axios.get(`/api/student/${studentId}`)
          .then(res => {
            console.log("FETCH STUDENTDETAIL GET RES", res);
            this.studentname = res.data.student_name;
            console.log("student name :", this.student_name)
            this.TestList = res.data.tests;
            console.log("TestList : ", this.TestList)
          })
          .catch(err => {
            console.log("FETCH STUDENTDETAIL GET ERR.RESPONSE", err.response);
            alert(`${err.response.status} ${err.response.statusText}`);
          }); -->
      }
    }
  }

  Vue.createApp(TestListApp).mount('#page-top');
</script>

templates/include/test_submit_vue.html
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>
  const TestSubmitApp = {
    delimiters: ['[[', ']]'],
    data() {
      return {
        csrfToken: document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
        ExamYearSemester: "",
        ExamGrade: "",
        region: "",
        answers: [],
        answerList: Array.from({ length: 5 }, () => Array(5).fill(null)),
        studentId: '',
      };
    },
    created() {
      console.log("created()...");
      let path = location.pathname;
      if (!path.endsWith('/')) {
          path += '/';
      }
      this.studentId = path.split('/').slice(-2)[0];
      console.log("studentId : ", this.studentId);
    },
    methods: {
      submitForm() {
        // FormData 인스턴스 생성
        const formData = new FormData();
        
        // 데이터 추가
        formData.append('ExamYearSemester', this.ExamYearSemester);
        formData.append('ExamGrade', this.ExamGrade);
        formData.append('ExamArea', this.region);  // "region" 필드를 "ExamArea"로 매핑
        const numericAnswerList = this.answerList.flat().map(answer => Number(answer));
        formData.append('ExamResults', JSON.stringify(numericAnswerList));
        formData.append('StudentId', String(this.studentId));
  
        // answerList의 모든 항목을 평탄화하여 추가
        // this.answerList.flat().forEach((answer, index) => {
        //   formData.append(`answers[${index}]`, answer);
        // });

        for (let [key, value] of formData.entries()) {
          console.log(key, value);
      }
        
        axios.post(`/api/report/result/${this.studentId}/`, formData, {
          headers: {
            'X-CSRFToken': this.csrfToken, // CSRF 토큰 헤더에 추가
            'Content-Type': 'multipart/form-data' // 중요: FormData를 사용할 때의 Content-Type
          }
        })
        .then(response => {
          console.log("Submit response:", response);
          window.location.href = `/report/result/${this.studentId}/?year_semester=${this.ExamYearSemester}&test_grade=${this.ExamGrade}`;
        })
        .catch(error => {
          console.error("Submit error:", error.response);
          alert(`${error.response.status} ${error.response.statusText}`);
        });
      }
    },
  }
  Vue.createApp(TestSubmitApp).mount('#page-top');
  </script>
  