api/urls.py
from django.urls import path

from api import views


app_name = 'api'
urlpatterns = [
    path('student/list', views.ApiStudentLV.as_view(), name='student_list'),
    path('student/add', views.AddStudentCV.as_view(), name='student_list'),
    path('student/<int:student_id>/', views.ApiStudentDV.as_view(), name='student_detail'),
    path('report/submit/<int:student_id>/', views.ApiSubmitCV.as_view(), name='submit'),
    path('report/result/<int:student_id>/', views.ApiResultLV.as_view(), name='result'),
    path('report/detail/<int:student_id>/', views.ApiReportLV.as_view(), name='result'),
]

dashboard/urls.py
from django.urls import path

from dashboard import views


app_name = 'dashboard'
urlpatterns = [
    # /dashboard/student/99/
    path('student/<int:pk>/', views.StudentDV.as_view(), name='student_detail'),
    path('testlist', views.TestDV.as_view(), name='testlist'),
    path('addstudent/', views.AddStudentCV.as_view(), name='add_student'),
    path('student/update/<int:pk>/', views.StudentUV.as_view(), name='student-update'),
]

mpitest/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from mpitest.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('report/', include('report.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users.views import CustomPasswordChangeView, EditUserProfileView, PaymentResultView, PaymentSuccessView, PaymentView, SignUpView, CustomLoginView

app_name = "users"
urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', EditUserProfileView.as_view(), name='profile'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('payment/result/', PaymentResultView.as_view(), name='payment_result'),
    path('payment/success/', PaymentSuccessView.as_view(), name='payment_success'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
        integrity="sha512-qZvrmS2ekKPF2mSznTQsxqPgnpkI4DNTlrdUmTzrDgektczlKNRRhy5X5AAOnx5S09ydFYWWNSfcEqDTTHgtNA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block extra-style %}{% endblock %}
</head>

<body>
    <div id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top"><img src="{% static 'assets/nav_logo.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">학원생</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:testlist' %}">시험지</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <!-- Dropdown for user information -->
                            <div class="dropdown">
                                <button class="btn btn-outline-light dropdown-toggle" type="button"
                                    id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username }}님
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">프로필</a></li>
                                    {% comment %} <li><a class="dropdown-item" href="{% url 'users:edit_profile' %}">설정</a></li> {% endcomment %}
                                    <li><a class="dropdown-item" href="{% url 'users:change_password' %}">비밀번호 변경</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li>
                                        <form method="post" action="{% url 'users:logout' %}">
                                            {% csrf_token %}
                                            <button type="submit" class="dropdown-item">로그아웃</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                            {% else %}
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-outline-light"><a
                                        href="{% url 'users:login' %}">Log in</a></button>
                                <button type="button" class="btn btn-light"><a href="{% url 'users:signup' %}">Sign
                                        Up</a></button>
                            </div>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">MPI TEST</div>
                <div>MPI(Mathematical Potential Index) :
                    수리적 능력. 즉, 기초적인 수리 능력을 진단하고 그 요인이 되는 계산력, 이해력, 추론력, 문제해결력의 네 가지 요인별로 수리적 정보 처리 능력을 측정합니다. 학생의 현재
                    수리언어의 처리 능력을 종합적으로 진단합니다. 이 결과와 본 연구소의 통계 데이터를 기반으로 자체 개발한 AI가 중·고등학교에서의 성적을 정밀 예측합니다.</div>
            </div>
        </header>

        {% block content %}
        {% endblock %}

        {% block footer %}{% endblock %}
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    {% block extra-script %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}home.html{% endblock %}

{% block content %}
<!-- Student Grid-->
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">학생 목록</h2>
            <h3 class="section-subheading text-muted">학생의 목록을 확인할 수 있습니다.</h3>
        </div>
        <div class="d-flex flex-column w-100">
            <div class="d-flex flex-row-reverse w-100">
                <button class="btn btn-warning" type="button">
                    <a :href="`/dashboard/addstudent/`" class="text-black" style="text-decoration: none;">학생 추가</a>
                </button>
            </div>
            <!-- Student List Tabel -->
            <div class="mb-5">
                <div class="mb-3 fs-4 table-top-line container text-center">
                    <div class="row align-items-start">
                        <div class="col-2">이름</div>
                        <div class="col-1">학년</div>
                        <div class="col-3">생년월일</div>
                        <div class="col-3">시험정보</div>
                        <div class="col-3">정보수정</div>
                    </div>
                </div>
                <hr>
                <div v-for="student in studentList" :key="student.name"
                    class="mt-3 mb-3 fs-5 table-top-line container text-center">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-2">[[ student.name ]]</div>
                        <div class="col-1">[[ student.grade ]]</div>
                        <div class="col-3">[[ student.birthdate ]]</div>
                        <div class="col-3">
                            <button class="btn btn-info btn-lg" type="button">
                                <a :href="`/dashboard/student/${student.id}/`" class="text-black"
                                    style="text-decoration: none;">시험정보</a></button>
                        </div>
                        <div class="col-3">
                            <button class="btn btn-primary btn-lg" type="button">
                                <a :href="`/dashboard/student/update/${student.id}/`" class="text-light"
                                    style="text-decoration: none;">정보
                                    수정</a>
                            </button>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>

</section>

{% endblock %}

{% block footer %}
<!-- Footer-->
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2023</div>
            <div class="col-lg-4 my-3 my-lg-0">
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i
                        class="fab fa-twitter"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i
                        class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i
                        class="fab fa-linkedin-in"></i></a>
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

{% block extra-script %}
{% include 'include/student_list_vue.html' %}
{% endblock %}