api/urls.py
from django.urls import path

from api import views


app_name = 'api'
urlpatterns = [
    path('student/list', views.ApiStudentLV.as_view(), name='student_list'),
    path('student/add', views.AddStudentCV.as_view(), name='student_list'),
    path('student/<int:student_id>/', views.ApiStudentDV.as_view(), name='student_detail'),
    path('report/submit/<int:student_id>/', views.ApiSubmitCV.as_view(), name='submit'),
    path('report/result/<int:student_id>/', views.ApiResultLV.as_view(), name='result'),
    path('report/detail/<int:student_id>/', views.ApiReportLV.as_view(), name='result'),
]

mpitest/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from mpitest.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('report/', include('report.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users.views import CustomPasswordChangeView, EditUserProfileView, PaymentResultView, PaymentSuccessView, PaymentView, SignUpView, CustomLoginView

app_name = "users"
urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', EditUserProfileView.as_view(), name='profile'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('payment/result/', PaymentResultView.as_view(), name='payment_result'),
    path('payment/success/', PaymentSuccessView.as_view(), name='payment_success'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    affiliation = models.CharField(max_length=100, verbose_name='학원명')  # 학원명 필드 추가
    region = models.CharField(max_length=100, verbose_name='지역권역')  # 최대 길이 증가
    region_detail = models.CharField(max_length=100, verbose_name='세부주소')  # 최대 길이 조정
    terms_agreed = models.BooleanField(default=False, verbose_name='전자상거래 표준약관 동의')
    license = models.IntegerField(default=5, verbose_name='사용권(남은 횟수)')
    total_report_gen = models.PositiveIntegerField(default=0, verbose_name='보고서 생성 횟수')
    
    phone_regex = RegexValidator(regex=r'^\d{3}-\d{4}-\d{4}$', message="핸드폰 번호는 다음의 형식이어야 합니다 : '000-0000-0000'.")
    telephone = models.CharField(validators=[phone_regex], max_length=17, blank=True, verbose_name='핸드폰 번호')

    def __str__(self):
        return f"{self.user.username}'s profile"

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imp_uid = models.CharField(max_length=255)  # 포트원 결제 고유 ID
    merchant_uid = models.CharField(max_length=255)  # 가맹점 고유 ID
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # 결제 금액
    status = models.CharField(max_length=50)  # 결제 상태
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Payment {self.imp_uid} by {self.user.username}'

users/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from users.models import UserProfile

REGION_CHOICES = [
    ('강남서초', '강남서초'),
    ('강동송파', '강동송파'),
    ('강서양천', '강서양천'),
    ('서울남부', '서울남부(영등포,구로,금천)'),
    ('서울동부', '서울동부(동대문,중랑)'),
    ('동작관악', '동작관악'),
    ('서울북부', '서울북부(도봉,노원)'),
    ('서울서부', '서울서부(서대문,마포,은평)'),
    ('성동광진', '성동광진'),
    ('성북강북', '성북강북'),
    ('서울중부', '서울중부(종로,중구,용산)'),
]

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(required=True, label='사용자 이름',)
    password1 = forms.CharField(required=True, label='비밀번호 입력', widget=forms.PasswordInput,)
    password2 = forms.CharField(required=True, label='비밀번호 확인', widget=forms.PasswordInput,)
    email = forms.EmailField(required=True, label='이메일 주소')
    affiliation = forms.CharField(required=True, label='소속 학원 이름')
    region = forms.ChoiceField(required=True, label='교육청 지역 권역', choices=REGION_CHOICES)
    region_detail = forms.CharField(required=True, label='세부주소')
    terms_agreed = forms.BooleanField(required=True, label='전자상거래 표준약관 동의')
    telephone_part1 = forms.CharField(max_length=3, required=True, label='핸드폰 번호 앞자리', initial='010', widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    telephone_part2 = forms.CharField(max_length=4, required=True, label='핸드폰 번호 중간자리')
    telephone_part3 = forms.CharField(max_length=4, required=True, label='핸드폰 번호 뒷자리')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'affiliation', 'region', 'region_detail', 'terms_agreed')
        
    def clean_region_detail(self):
        region_detail = self.cleaned_data.get('region_detail')
        # 정규 표현식을 사용하여 "XX구 YY동" 형태와 일치하는지 검사
        pattern = re.compile(r'^[\w가-힣]+구 [\w가-힣]+동$')
        
        if not pattern.match(region_detail):
            raise forms.ValidationError('올바른 형태의 세부주소를 입력하세요. 예: 강남구 개포동')
        return region_detail
    
    def clean(self):
        cleaned_data = super().clean()
        telephone_part1 = cleaned_data.get('telephone_part1') or '010'
        print("part1 : ", telephone_part1)
        telephone_part2 = cleaned_data.get('telephone_part2')
        print("part2 : ", telephone_part2)
        telephone_part3 = cleaned_data.get('telephone_part3')
        print("part3 : ", telephone_part3)
        
        if telephone_part1 and telephone_part2 and telephone_part3:
            telephone = f'{telephone_part1}-{telephone_part2}-{telephone_part3}'
            cleaned_data['telephone'] = telephone
        else:
            raise forms.ValidationError('핸드폰 번호를 올바르게 입력해주세요.')

        return cleaned_data

    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            # 이미 존재하는 UserProfile이 있는지 확인
            if not UserProfile.objects.filter(user=user).exists():
                UserProfile.objects.create(
                    user=user,
                    affiliation=self.cleaned_data['affiliation'],
                    region=self.cleaned_data['region'],
                    region_detail=self.cleaned_data['region_detail'],
                    terms_agreed=self.cleaned_data['terms_agreed'],
                    telephone=self.cleaned_data['telephone'],
                )
        return user

class UserProfileForm(forms.ModelForm):
    region = forms.ChoiceField(choices=REGION_CHOICES, required=True, label='교육청 지역 권역')

    class Meta:
        model = UserProfile
        fields = ['affiliation', 'region', 'region_detail', 'telephone', 'terms_agreed']
        labels = {
            'affiliation': '학원명',
            'region': '지역권역',
            'region_detail': '세부주소',
            'telephone': '핸드폰 번호',
        }
        widgets = {
            'telephone': forms.TextInput(attrs={
                'placeholder': '000-0000-0000',
                'pattern': r'\d{3}-\d{4}-\d{4}',
                'title': '핸드폰 번호는 다음의 형식이어야 합니다 : 000-0000-0000'
            }),
        }

class CustomPasswordChangeForm(PasswordChangeForm):
    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.user
        if not authenticate(username=user.username, password=old_password):
            raise forms.ValidationError("입력하신 현재 비밀번호가 틀립니다.")
        return old_password

    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        # 필드의 레이블, 헬프 텍스트, 위젯 속성 등을 설정할 수 있습니다.
        self.fields['old_password'].label = _("현재 비밀번호")
        self.fields['new_password1'].label = _("새 비밀번호")
        self.fields['new_password2'].label = _("새 비밀번호 확인")
        
        # 필드의 placeholder 설정
        self.fields['old_password'].widget.attrs.update({'placeholder': _('현재 비밀번호 입력')})
        self.fields['new_password1'].widget.attrs.update({'placeholder': _('새 비밀번호 입력')})
        self.fields['new_password2'].widget.attrs.update({'placeholder': _('새 비밀번호 확인')})

    def clean_new_password2(self):
        # 새 비밀번호 확인 필드 검증 로직
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("새 비밀번호가 일치하지 않습니다."))
        return password2

    def save(self, commit=True):
        # 비밀번호 변경 로직
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["new_password1"])
        if commit:
            user.save()
        return user

users/views.py
import json
import os
import requests
from .models import Payment, UserProfile
from .forms import CustomUserCreationForm, UserProfileForm, CustomPasswordChangeForm
from django.conf import settings
from django.contrib.auth import authenticate,login,update_session_auth_hash
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# 텍스트 파일 읽기 함수
def read_text_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

# 회원가입 뷰
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

    def form_valid(self, form):
        # 폼이 유효할 경우, 사용자를 로그인 시키고 success_url로 리다이렉트합니다.
        user = form.save()
        print("User created:", user)
        login(self.request, user)
        print("User logged in:", user)
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print("Form is invalid")
        print(form.errors)
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        # 기존의 context를 가져옵니다.
        context = super().get_context_data(**kwargs)
        
        # 텍스트 파일의 내용을 읽어옵니다.
        file_path = os.path.join(settings.BASE_DIR, 'users', 'e-comm_yakgwan.txt')
        file_content = read_text_file(file_path)
        
        # 텍스트 파일 내용을 context에 추가합니다.
        context['file_content'] = file_content
        
        return context
    
class CustomLoginView(LoginView):
    template_name = 'users/login.html'

    # form_valid 메서드는 로그인이 성공했을 때 호출됩니다.
    def form_valid(self, form):
        login(self.request, form.get_user())
        return redirect(self.get_success_url())

    # form_invalid 메서드는 로그인이 실패했을 때 호출됩니다.
    def form_invalid(self, form):
        messages.error(self.request, "아이디 또는 비밀번호가 틀렸습니다")
        return super().form_invalid(form)

    # 로그인 성공 후 리다이렉트할 URL을 지정합니다.
    def get_success_url(self):
        return reverse_lazy('home')  # 원하는 성공시 리다이렉트 URL로 변경해주세요.

    # 로그인 성공 여부에 관계 없이 항상 호출됩니다. 
    def post(self, request, *args, **kwargs):
        # super().post 메서드는 form_valid 또는 form_invalid를 호출합니다.
        return super().post(request, *args, **kwargs)

class EditUserProfileView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        # 이 메소드는 로그인한 사용자의 UserProfile을 반환하거나 존재하지 않으면 생성합니다.
        profile, created = UserProfile.objects.get_or_create(user=self.request.user)
        return profile

    def get_initial(self):
        # 텔레폰 부분을 분할하여 초기 데이터를 설정
        initial = super().get_initial()
        telephone_parts = self.object.telephone.split('-') if self.object.telephone else ["010", "", ""]
        initial.update({
            'telephone_part1': telephone_parts[0],
            'telephone_part2': telephone_parts[1],
            'telephone_part3': telephone_parts[2],
        })
        return initial

    def form_valid(self, form):
        # 폼 데이터가 유효할 때 호출
        telephone = f"{self.request.POST.get('telephone_part1')}-{self.request.POST.get('telephone_part2')}-{self.request.POST.get('telephone_part3')}"
        form.instance.telephone = telephone
        form.instance.user = self.request.user  # 사용자 인스턴스 자동 할당
        response = super().form_valid(form)
        messages.success(self.request, '프로필이 성공적으로 업데이트 되었습니다.')  # 성공 메시지 추가
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_profile'] = self.object
        return context

class CustomPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('home')  # 성공 시 리다이렉션할 URL
    template_name = 'users/change_password.html'
    success_message = "비밀번호가 성공적으로 변경되었습니다."

    def form_valid(self, form):
        # 폼이 유효하면 호출되는 메소드
        response = super().form_valid(form)
        # 세션 업데이트 로직
        update_session_auth_hash(self.request, self.request.user)
        return response



@method_decorator(login_required, name='dispatch')
class PaymentView(View):
    def get(self, request):
        profile = UserProfile.objects.get(user=request.user)
        context = {
            'api_key': settings.PORTONE_API_KEY,
            'user_profile': profile,
        }
        return render(request, 'users/payment.html', context)
    
class PaymentResultView(View):
    def post(self, request):
        data = json.loads(request.body)
        imp_uid = data.get('imp_uid')
        merchant_uid = data.get('merchant_uid')
        payment_type = data.get('payment_type')
        
        response = self.verify_payment(imp_uid)
        
        if response['status'] == 'success':
            amount = response['response']['amount']
            user_profile = UserProfile.objects.get(user=request.user)
            if payment_type == 'single':
                user_profile.license += 1
            elif payment_type == 'bulk':
                user_profile.license += 10
            user_profile.save()
            
            Payment.objects.create(
                user=request.user,
                imp_uid=imp_uid,
                merchant_uid=merchant_uid,
                amount=amount,
                status='paid'
            )
            return JsonResponse({'status': 'success', 'message': 'Payment was successful'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Payment verification failed'})

    def verify_payment(self, imp_uid):
        url = "https://api.iamport.kr/payments/{imp_uid}".format(imp_uid=imp_uid)
        headers = {
            'Authorization': 'Bearer ' + self.get_access_token()
        }
        response = requests.get(url, headers=headers)
        return response.json()

    def get_access_token(self):
        url = "https://api.iamport.kr/users/getToken"
        data = {
            'imp_key': settings.PORTONE_API_KEY,
            'imp_secret': settings.PORTONE_API_SECRET
        }
        response = requests.post(url, data=data)
        return response.json()['response']['access_token']

class PaymentSuccessView(View):
    def get(self, request):
        return render(request, 'users/payment_success.html')

templates/users/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card card-body">
                <h2 class="text-center mb-4">비밀번호 변경</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.old_password.id_for_label }}" class="form-label">현재 비밀번호</label>
                        <input type="password" name="{{ form.old_password.name }}" id="{{ form.old_password.id_for_label }}" class="form-control {% if form.old_password.errors %}is-invalid{% endif %}" required>
                        {% for error in form.old_password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.new_password1.id_for_label }}" class="form-label">새 비밀번호</label>
                        <input type="password" name="{{ form.new_password1.name }}" id="{{ form.new_password1.id_for_label }}" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}" required>
                        {% for error in form.new_password1.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.new_password2.id_for_label }}" class="form-label">새 비밀번호 확인</label>
                        <input type="password" name="{{ form.new_password2.name }}" id="{{ form.new_password2.id_for_label }}" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}" required>
                        {% for error in form.new_password2.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-primary w-100">비밀번호 변경</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block extra_script %}
{% include 'include/chagne_password_vue.html' %}
{% endblock %}

templates/users/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card card-body">
                <h2 class="text-center mb-4">프로필 수정</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_affiliation" class="form-label">학원명</label>
                        <input type="text" name="affiliation" id="id_affiliation" class="form-control" value="{{ form.affiliation.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <label for="id_region" class="form-label">지역권역</label>
                        <select name="region" id="id_region" class="form-control">
                            <option value="">교육청 권역을 선택해주세요</option>
                            {% for value, label in form.region.field.choices %}
                            <option value="{{ value }}" {% if form.region.value == value %}selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_region_detail" class="form-label">세부주소</label>
                        <input type="text" name="region_detail" id="id_region_detail" class="form-control" value="{{ form.region_detail.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <label for="telephone" class="mt-3 mb-1">{{ form.telephone.label }}</label>
                        <input type="text" class="form-control" id="telephone" name="{{ form.telephone.name }}" value="{{ form.telephone.value|default_if_none:'' }}" placeholder="000-0000-0000" required pattern="\d{3}-\d{4}-\d{4}" title="Phone number must be entered in the format: 000-0000-0000" oninvalid="this.setCustomValidity('핸드폰 번호를 입력해주세요')" oninput="this.setCustomValidity('')">
                    </div>
                    <button type="submit" class="btn btn-primary">변경 사항 저장</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="mb-3 text-center">로그인</h1>
      <form method="post" action="{% url 'users:login' %}" class="card card-body">
        {% csrf_token %}

        {% if messages %}
        <script type="text/javascript">
        window.onload = function() {
            {% for message in messages %}
            alert('{{ message }}');
            {% endfor %}
        }
        </script>
        {% endif %}

        <div class="mb-3">
          <label for="username" class="form-label">사용자 ID</label>
          <input type="text" name="username" id="username" class="form-control" placeholder="사용자 ID를 입력하세요" required oninvalid="this.setCustomValidity('사용자 ID를 입력해주세요')" oninput="this.setCustomValidity('')">

        </div>
        <div class="mb-3">
          <label for="password" class="form-label">비밀번호</label>
          <input type="password" name="password" id="password" class="form-control" placeholder="비밀번호를 입력하세요" required oninvalid="this.setCustomValidity('비밀번호를 입력해주세요')" oninput="this.setCustomValidity('')">
        </div>
        <button type="submit" class="btn btn-primary w-100">로그인</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra-script %}
{% include 'include/auth_vue.html' %}
{% endblock %}

templates/users/payment.html
{% extends 'base.html' %}

{% block title %}Payment{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>결제하기</h2>
    <form id="paymentForm">
        <div class="form-group">
            <label for="paymentType">결제 종류</label>
            <select class="form-control" id="paymentType" name="paymentType">
                <option value="single">단일 결제</option>
                <option value="bulk">대량 결제</option>
            </select>
        </div>
        <button type="button" class="btn btn-primary mt-3" onclick="initiatePayment()">결제 진행</button>
    </form>
</div>
{% endblock %}

{% block extra-script %}
{% include 'include/payment_vue.html' with api_key=api_key user_profile=user_profile %}
{% endblock %}

templates/users/payment_success.html
{% extends 'base.html' %}

{% block title %}Payment Success{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>결제가 완료되었습니다.</h2>
    <p>사용권이 추가되었습니다. 이제 서비스를 이용하실 수 있습니다.</p>
    <a href="{% url 'home' %}" class="btn btn-primary">돌아가기</a>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="mb-3 text-center">{{ user.username }}님의 프로필</h1>
      <div class="card card-body">
        <form method="post" id="profileForm" class="needs-validation" novalidate>
          {% csrf_token %}
          
          <div class="form-group">
            <label for="affiliation" class="mt-3 mb-1">{{ form.affiliation.label }}</label>
            <input type="text" class="form-control" id="affiliation" name="{{ form.affiliation.name }}" value="{{ form.affiliation.value }}" placeholder="학원명을 입력하세요" required oninvalid="this.setCustomValidity('학원명을 입력해주세요')" oninput="this.setCustomValidity('')">
          </div>
          
          <div class="form-group">
            <label for="region" class="mt-3 mb-1">{{ form.region.label }}</label>
            <input type="text" class="form-control" id="region" name="{{ form.region.name }}" value="{{ form.region.value }}" placeholder="지역권역을 입력하세요" required oninvalid="this.setCustomValidity('지역권역을 입력해주세요')" oninput="this.setCustomValidity('')">
          </div>

          <div class="form-group">
            <label for="region_detail" class="mt-3 mb-1">{{ form.region_detail.label }}</label>
            <input type="text" class="form-control" id="region_detail" name="{{ form.region_detail.name }}" value="{{ form.region_detail.value }}" placeholder="세부주소를 입력하세요" required oninvalid="this.setCustomValidity('세부주소를 입력해주세요')" oninput="this.setCustomValidity('')">
          </div>

          <div class="form-group">
            <label for="telephone" class="mt-3 mb-1">{{ form.telephone.label }}</label>
            <div class="d-flex">
                <input type="text" class="form-control" id="telephone_part1" name="telephone_part1" maxlength="3" value="{{ form.initial.telephone_part1 }}" readonly>
                <span class="mx-2">-</span>
                <input type="text" class="form-control" id="telephone_part2" name="telephone_part2" maxlength="4" value="{{ form.initial.telephone_part2 }}" required oninvalid="this.setCustomValidity('핸드폰 번호를 입력해주세요')" oninput="this.setCustomValidity('')">
                <span class="mx-2">-</span>
                <input type="text" class="form-control" id="telephone_part3" name="telephone_part3" maxlength="4" value="{{ form.initial.telephone_part3 }}" required oninvalid="this.setCustomValidity('핸드폰 번호를 입력해주세요')" oninput="this.setCustomValidity('')">
            </div>
          </div>

          <div class="form-group">
            <div class="d-flex justify-content-around mt-3 mb-1">
                <div class="d-flex justify-content-between my-3 mx-4">
                    <div class="mx-5 pt-3 pb-2">사용권(남은 횟수)</div>
                    <div class="card px-5 py-2 text-primary fs-4 fw-bolder">{{ user_profile.license }}</div>
                </div>
                <div class="d-flex justify-content-between my-3 mx-4">
                    <div class="mx-5 pt-3 pb-2">보고서 생성 횟수</div>
                    <div class="card px-5 py-2 text-success fs-4 fw-bolder">{{ user_profile.total_report_gen }}</div>
                </div>
            </div>
          </div>

          <button type="submit" class="btn btn-primary w-100 mt-3">프로필 업데이트</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra-script %}
<script>
  // Custom validation script if needed
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      var forms = document.getElementsByClassName('needs-validation');
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
{% endblock %}